# Site settings
title: wijihye
description: >
  Jihye's records
author: Jihye
email: wijihye@naver.com
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
github_username: https://github.com/wijihye

disqus_shortname: YourDisqusShortname

# Build settings
include: [_pages]
markdown: kramdown
asset_url: /assets # icon이나 png등의 요소들
permalink: /:year/:month/:title
sass:
  style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
